config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  root :to => 'location#index'

  devise_for :users

  patch '/location/:id/itinerary' => 'location#itinerary', as: 'itinerary'
  patch '/location/:id/remove_itinerary' => 'location#remove_itinerary', as: 'remove_itinerary'
  get '/location/search' => 'location#search', as: 'search'
  get '/location/popular' => 'location#popular', as: 'popular'
  get '/location/hidden_gems' => 'location#hidden_gems', as: 'hidden_gems'
  get '/location/all' => 'location#all', as: 'all'

  resources :users, :only => [:show]

  resources :location, :only => [:index,:show] do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :location
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  belongs_to :location
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :users
  has_many :comments
  has_many :images

  def self.search(search)
    where("name ilike ?","%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :locations
  has_many :comments
  has_many :images
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def user_itinerary
    @locations = []
    self.itinerary.each do |itinerary|
      @locations.push(Location.find(itinerary))
    end
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

  def search
    search_result = params[:search]
    if search_result
      @searched_locations = Location.search(search_result).order("created_at DESC")
    else
      @searched_locations = Location.all.order("created_at DESC")
    end
  end

  def create
  end

 def new
 end

 def delete
 end

 def itinerary
   user = current_user
   location_id = params[:id].to_i
   location = Location.find(location_id)
   user.itinerary.push(location_id)
   if user.save
     puts "saved"
   else
     binding.pry
     puts user.errors
   end
   redirect_to location_path(location)
 end

   def remove_itinerary
   user = current_user
   location_id = params[:id].to_i
   location = Location.find(location_id)
   user.itinerary.delete(location_id)
   user.save
   redirect_to location_path(location)
   end

   def popular
     @locations = Location.all
   end

   def hidden_gems
     @locations = Location.all
   end

   def all
     @locations = Location.all
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @locations = current_user.itinerary
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Antic+Slab" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister" rel="stylesheet">

    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
    <title>CapstoneProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div id="navbar navbar-left">
        <% if current_user %>
          <span class="glyphicon glyphicon-home"></span> <%= link_to "home", "/" %> | <span class="glyphicon glyphicon-user"></span> <%= link_to current_user.email, user_path(current_user) %> | <span class="glyphicon glyphicon-log-out"></span> <%= link_to "Sign out", destroy_user_session_path, :method =>'delete' %>
          <span class="navbar-right"> <%= form_tag(search_path, :method => "get", id: "search-form") do %>
             <%= text_field_tag :search, params[:search], placeholder: "Search Locations" %>
             <%= submit_tag "Search", :name => nil %>
           <% end %></span>
        <% else %>
          <span class="glyphicon glyphicon-home"></span> <%= link_to "home", "/" %> | <span class="glyphicon glyphicon-edit"></span> <%= link_to "Sign up", '/users/sign_up' %> | <span class="glyphicon glyphicon-user"></span> <%= link_to "Sign in", '/users/sign_in' %>
          <span class="navbar-right"> <%= form_tag(search_path, :method => "get", id: "search-form") do %>
             <%= text_field_tag :search, params[:search], placeholder: "Search Locations" %>
             <%= submit_tag "Search", :name => nil %>
           <% end %></span>
        <% end %>
     </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>
    <footer>
      <hr>
      <h4>Follow me on social media</h4>
      <ul class="social-networks spin-icon">
        <li><a href="https://www.linkedin.com/in/david-shin" class="icon-linkedin">LinkedIn</a></li>
        <li><a href="https://twitter.com/crispyb0i" class="icon-twitter">Twitter</a></li>
        <li><a href="https://github.com/crispyb0i" class="icon-github">GitHub</a></li>
        <li><a href="https://twitch.tv/crispyb0i" class="icon-twitch">Twitch</a></li>
        <li><a href="https://instagram.com/crispyb0i" class="icon-instagram">Instagram</a></li>
      </ul>
    </footer>
  </body>
</html>

app/views/location/all.html.erb
<h1>All Locations</h1>

<% @locations.each do |location| %>
    <div class="col-md-3 img-thumbnail">
      <a href="/location/<%=location.id%>">
        <div>
        <h4><%=location.name%></h4>
          <img class="img-rounded main_image" src="<%=location.main_image%>" alt="<%= location.name %>">
        </div>
      </a>
    </div>
  <% end %>

app/views/location/hidden_gems.html.erb
<div id="hiddenGems">
  <h1>Hidden Gems</h1>

  <div class="row">
    <% @locations.each do |location| %>
      <% if !location.main_attraction %>
        <div class="col-md-3 img-thumbnail">
          <a href="/location/<%=location.id%>">
            <div>
            <h4><%=location.name%></h4>
              <img class="img-rounded main_image" src="<%=location.main_image%>" alt="<%= location.name %>">
            </div>
          </a>
          <br>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/location/index.html.erb
<br><br><br>
<div id="header">
  <h1 id="main_title">Welcome to Seattle</h1>
  <img id="homepage_image" class="img-rounded" src="http://davidbalyeat.com/wp-content/uploads/seattle-skyline-night-space-needle-mount-rainier-high-definition-hd-professional-photography.jpg" alt="">
  <a href="https://www.accuweather.com/en/us/seattle-wa/98104/weather-forecast/351409" class="aw-widget-legal"></a>
  <div id="awcc1501020395773" class="aw-widget-current"  data-locationkey="351409" data-unit="f" data-language="en-us" data-useip="false" data-uid="awcc1501020395773"></div>
  <script type="text/javascript" src="https://oap.accuweather.com/launch.js"></script>
</div>
<div id="featured_locations">
  <a href="/location/popular">
    <h3>Popular Attractions</h3>
  </a>
  <div class="row featured">
    <% @locations.limit(8).each do |location| %>
      <% if location.main_attraction %>
        <div class="col-md-3 img-thumbnail">
          <a href="/location/<%=location.id%>">
            <div>
            <h4><%=location.name%></h4>
              <img class="img-rounded main_image" src="<%=location.main_image%>" alt="<%= location.name %>">
            </div>
          </a>
          <br>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
  <div id="hiddenGems">
    <a href="/location/hidden_gems">
      <h3>Hidden Gems</h3>
    </a>
    <div class="row">
      <% @locations.limit(17).each do |location| %>
        <% if !location.main_attraction %>
          <div class="col-md-3 img-thumbnail">
            <a href="/location/<%=location.id%>">
              <div>
              <h4><%=location.name%></h4>
                <img class="img-rounded main_image" src="<%=location.main_image%>" alt="<%= location.name %>">
              </div>
            </a>
            <br>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <br>
  <a id="all_page" href="/location/all">See all locations</a>
  <br><br>

app/views/location/popular.html.erb
<div id="featured_locations">
  <h1>Popular Attractions</h1>
  <div class="row featured">
    <% @locations.each do |location| %>
      <% if location.main_attraction %>
        <div class="col-md-3 img-thumbnail">
          <a href="/location/<%=location.id%>">
            <div>
            <h4><%=location.name%></h4>
              <img class="img-rounded main_image" src="<%=location.main_image%>" alt="<%= location.name %>">
            </div>
          </a>
          <br>
          </div>
        <% end %>

    <% end %>
  </div>
</div>

app/views/location/search.html.erb
<h1>Your search results:</h1>
<% if @searched_locations == [] %>
  <h4>Search results not found</h4>
<% else %>
  <% @searched_locations.each do |location| %>
    <div class="col-md-4 img-thumbnail">
      <a href="/location/<%=location.id%>"><div>
        <h4><%=location.name%></h4>
          <img id="search_picture" class="img-rounded main_image" src="<%=location.main_image%>" alt="<%= location.name %>">
        </div>
      </a>
      <br>
    </div>
  <% end %>
<% end %>

app/views/location/show.html.erb
<h1 class="jumbotron"><%=@location.name%></h1>

<h4><%=@location.description%></h4>
<br>
<h4><span class="glyphicon glyphicon-globe"></span> <a href="<%=@location.website%>">website</a> |
  <% if @location.phone_number != "n/a"%>
    <span class="glyphicon glyphicon-phone"><%=@location.phone_number%></span> |
  <% end %>
  <span class="glyphicon glyphicon-map-marker"></span> <%=@location.street_address%> <%=@location.city_state%></h4>
<img src="<%=@location.main_image%>" class="img-rounded" alt="">
<br>
<% if current_user %>
  <% if current_user.itinerary.include?(@location.id) %>
    <%= button_to 'Remove from itinerary', remove_itinerary_path, :class => "btn btn-danger", :method => :patch%>
  <% else %>
    <%= button_to 'Add to itinerary', itinerary_path, :class => "btn btn-primary", :method => :patch %>
  <% end %>
  <% else %>

    <h4><a href="/users/sign_in">Sign in</a> to add to Itinerary</h4>

<% end %>
<br>

app/views/users/show.html.erb
<h1><%=current_user.email%></h1>
<% if current_user.itinerary.length == 0 %>
  <h3>There are currently no locations in your itinerary</h3>
<% else %>
<h3>Your Itinerary:</h3>
  <div class="row">
    <% @locations.each do |location| %>
      <a href="/location/<%=location%>"><div>
        <div class="col-md-4">
          <h4><%=Location.find(location).name%></h4>
          <img id="itinerary_images" src="<%=Location.find(location).main_image%>" alt="" class="img-rounded">
        </div>
      </div></a>
    <% end %>
  </div>
<% end %>